### ISSUE TITLE
Channel list empty

### ISSUE THREAD

**Issue by reizhafajrian** [sendbird/sendbird-uikit-sample-react-native-expo#2]
when i try to testing it with this example the channel list always send empty array

**Comment by reizhafajrian** [comment]
![simulator_screenshot_9D87559A-1350-466E-A344-404F5AA9FC91](https://github.com/sendbird/sendbird-uikit-sample-react-native-expo/assets/65649495/1e40feed-d97b-44c7-a574-dd90d1d893e4)

**Comment by reizhafajrian** [comment]
![image](https://github.com/sendbird/sendbird-uikit-sample-react-native-expo/assets/65649495/12062888-c13b-4f0d-a4e5-be505353aaa1)
also when i try to console log the package it always send empty group channels too

**Comment by reizhafajrian** [comment]
but when I try with API response there is a group channel list

**Comment by bang9** [comment]
@reizhafajrian hello, sorry for inconvenience.
Could you update the chat sdk version to `v4.9.10` ?

**Comment by reizhafajrian** [comment]
yes it solve thanks
