### ISSUE TITLE
Expo Notif

### ISSUE THREAD

**Issue by reizhafajrian** [sendbird/sendbird-uikit-sample-react-native-expo#4]
so since this is using expo,is expo push token notifications can work in managed workflow?because the docs is only support fcm,apns,and huawei

**Comment by bang9** [comment]
Hello, we don't support Expo push tokens. Instead, you can use FCM/APNS tokens.

Please check the Expo documents for more information: https://docs.expo.dev/versions/latest/sdk/notifications/#getdevicepushtokenasync

<img width="893" alt="image" src="https://github.com/sendbird/sendbird-uikit-sample-react-native-expo/assets/26326015/af375b90-a5f2-46cd-b3f9-a238b62899ff">
