### ISSUE TITLE
WARN: Messages are already fetching.

### ISSUE THREAD

**Issue by smrubin** [sendbird/sendbird-uikit-sample-react-native-expo#6]
I followed the instructions in the readme and got the app up and running.

Occasionally, but a majority of the time, I am presented with the following log warning:
`WARN: Messages are already fetching.`

Is there any way to prevent this log or a better practice to use to avoid re-fetching?

**Comment by bang9** [comment]
Hi @smrubin, sorry for late response.

1. You can ignore logs using [LogBox](https://reactnative.dev/docs/0.70/debugging#console-errors-and-warnings).
2. You can set the log level of the Chat SDK to "none."
```ts
    <SendbirdUIKitContainer
      chatOptions={{
        logLevel: 0, // LogLevel.NONE
      }}
```

**Comment by smrubin** [comment]
Is there an alternative to just fix this warning? Don't really want to silence all logs coming from sendbird UIKit.

**Comment by bang9** [comment]
> Is there an alternative to just fix this warning? Don't really want to silence all logs coming from sendbird UIKit.

try `LogBox.ignoreLogs(['WARN: Messages are already fetching']);` as a temporary.
I'll try to make corrections to prevent duplicate requests.
